### ISSUE TITLE
icon looks bad.

### ISSUE THREAD

**Issue by ItsKruml** [Melodi17/GameLauncher#1]
The original icon is an eyesore, i have a proposal for a new icon, with dark mode version:

![Goofy launcher icon black](https://github.com/user-attachments/assets/f374d513-e733-40e1-b7da-b1784ab67a0c)
![Goofy launcher icon](https://github.com/user-attachments/assets/0a26a3be-75de-4b5e-83e4-6921685af920)

these also describe what the application does (Launch games for those that dont know)

**Comment by Melodi17** [comment]
Oh, I actually really like these! I'll try implementing them once I'm back at my desk. (Probably tomorrow or day after)

**Comment by ItsKruml** [comment]
I have no words... But sure I'd be honored for my artwork to be displayed here, all the minutes that went in to that payed off!

I also may update the design or try to upload the original .kri and .ico files

o(^▽^)o

**Comment by Melodi17** [comment]
Sorry for the late reply, can i get you to submit a pull request with the new images? Also a touch up on the dark mode one around the edges would be nice :D

**Comment by ItsKruml** [comment]
Yes in like 3 days if I remember.

**Comment by ItsKruml** [comment]
welll.... slight issue, i have just now rememberd that i wanted to do this, and in the meantime my os decided to leave the realm of the exsiting, also i have 0 idea on how pull requests work but ill try to fix the icons i uploaded here using my PhotoPea magic and try to figure out pull requests out RIGHT NOW :-)
